export const BORDER_CSS_KEYS = [
  'border',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'borderRadius',
  'borderTop',
  'borderRight',
  'borderBottom',
  'borderLeft',
  'borderBlockStart',
  'borderBlockEnd',
  'borderInlineStart',
  'borderInlineEnd',
  'borderInline',
  'borderBlock',
  'borderTopWidth',
  'borderTopStyle',
  'borderTopColor',
  'borderRightWidth',
  'borderRightStyle',
  'borderRightColor',
  'borderBottomWidth',
  'borderBottomStyle',
  'borderBottomColor',
  'borderLeftWidth',
  'borderLeftStyle',
  'borderLeftColor',
  'borderBlockStartWidth',
  'borderBlockStartStyle',
  'borderBlockStartColor',
  'borderBlockEndWidth',
  'borderBlockEndStyle',
  'borderBlockEndColor',
  'borderInlineStartWidth',
  'borderInlineStartStyle',
  'borderInlineStartColor',
  'borderInlineEndWidth',
  'borderInlineEndStyle',
  'borderInlineEndColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderStartStartRadius',
  'borderStartEndRadius',
  'borderEndStartRadius',
  'borderEndEndRadius',
  'borderInlineStartRadius',
  'borderInlineEndRadius',
  'borderTopRadius',
  'borderBottomRadius',
  'borderLeftRadius',
  'borderRightRadius',
] as const

export const BORDER_ALIASES = {
  rounded: 'borderRadius',
  roundedTop: ['borderTopLeftRadius', 'borderTopRightRadius'],
  roundedBottom: ['borderBottomLeftRadius', 'borderBottomRightRadius'],
  roundedLeft: ['borderTopLeftRadius', 'borderBottomLeftRadius'],
  roundedRight: ['borderTopRightRadius', 'borderBottomRightRadius'],
  roundedTopLeft: 'borderTopLeftRadius',
  roundedTopRight: 'borderTopRightRadius',
  roundedBottomLeft: 'borderBottomLeftRadius',
  roundedBottomRight: 'borderBottomRightRadius',
  borderStart: 'borderInlineStart',
  borderEnd: 'borderInlineEnd',
  borderX: ['borderLeft', 'borderRight'],
  borderY: ['borderTop', 'borderBottom'],
} as const
