export const LAYOUT_CSS_KEYS = [
  'width',
  'height',
  'minWidth',
  'minHeight',
  'maxWidth',
  'maxHeight',
  'minInlineSize',
  'maxInlineSize',
  'minBlockSize',
  'maxBlockSize',
  'inlineSize',
  'blockSize',
  'display',
  'overflow',
  'overflowX',
  'overflowY',
  'overscrollBehavior',
  'overscrollBehaviorX',
  'overscrollBehaviorY',
  'verticalAlign',
  'boxSizing',
  'boxDecorationBreak',
  'float',
  'objectFit',
  'objectPosition',
  'visibility',
  'isolation',
  'aspectRatio',
  /** ::before / ::after 等内容（Chakra `_after` 等） */
  'content',
] as const

export const LAYOUT_ALIASES = {
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  maxW: 'maxWidth',
  minH: 'minHeight',
  maxH: 'maxHeight',
  overscroll: 'overscrollBehavior',
  overscrollX: 'overscrollBehaviorX',
  overscrollY: 'overscrollBehaviorY',
} as const
