/** margin / padding 及逻辑属性（标准 CSS key） */
export const SPACE_CSS_KEYS = [
  'margin',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'marginBlockStart',
  'marginBlockEnd',
  'marginInlineStart',
  'marginInlineEnd',
  'marginInline',
  'marginBlock',
  'padding',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'paddingBlockStart',
  'paddingBlockEnd',
  'paddingInlineStart',
  'paddingInlineEnd',
  'paddingInline',
  'paddingBlock',
] as const

export const SPACE_ALIASES = {
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  mx: ['marginLeft', 'marginRight'],
  my: ['marginTop', 'marginBottom'],
  me: 'marginInlineEnd',
  marginEnd: 'marginInlineEnd',
  ms: 'marginInlineStart',
  marginStart: 'marginInlineStart',
  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  px: ['paddingInlineStart', 'paddingInlineEnd'],
  py: ['paddingTop', 'paddingBottom'],
  pe: 'paddingInlineEnd',
  paddingEnd: 'paddingInlineEnd',
  ps: 'paddingInlineStart',
  paddingStart: 'paddingInlineStart',
} as const
